FROM node:latest AS build 

RUN mkdir -p /home/usr/app

WORKDIR /home/usr/app

COPY package.json /home/usr/app/package.json
COPY package-lock.json /home/usr/app/package.lock.json

RUN npm install

COPY . /home/usr/app

RUN npm run build

FROM nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build /home/usr/app/dist /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon on;"]
