FROM python:3.10.7-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

EXPOSE 5000

COPY . .

CMD [ "gunicorn", "--bind" , "0.0.0.0:5000", "manage:app" ]
