FROM python:3.9-slim

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app

RUN python3 -m pip install -r requirements.txt

EXPOSE 8000

ENV FLASK_APP app.py
ENV FLASK_ENV development

ENTRYPOINT [ "flask"]

CMD ["run", "--host=0.0.0.0", "--port=8000"]
