FROM python:3.9-slim

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app

RUN python3 -m pip install -r requirements.txt

EXPOSE 8000:8000

ENTRYPOINT [ "flask" ]

CMD ["gunicorn"  , "-b", "0.0.0.0:8000", "app:app"]
